### ISSUE TITLE
Document how we expect game controls to work

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#178] opened 2023-01-01 21:06 UTC
Some relevant information from Discord conversations:

* How mouse interaction works in Civ 6: 
Less detail: https://discord.com/channels/1027393534627692645/1028004706435485766/1059197231393157171
More detail: https://discord.com/channels/1027393534627692645/1028004706435485766/1059203882569449482

* traditional RTS: https://discord.com/channels/1027393534627692645/1028004706435485766/1059195353875894313

* Factorio: https://discord.com/channels/1027393534627692645/1028004706435485766/1058949910889779243

**Comment by TimJentzsch** [comment] 2023-01-01 21:28
Potentially a duplicate of #174? :)

**Closed** 2023-01-01 22:19 UTC
Labels: ui, gameplay, game design
