### ISSUE TITLE
Think about ways to define items and recipes as an asset

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#189] opened 2023-01-02 20:41 UTC
We should have a textual format to define items and recipes which can be loaded as an asset.
This would enable us to iterate on the concrete numbers in a faster way.

For example, each recipe should define the input items and their counts, the time to craft the recipe, the structure to craft the recipe in and the number of output items.

For the items and structures it's probably enough to define a unique identifier (to use in the recipes) and maybe the textures/models needed to render them ingame

**Comment by alice-i-cecile** [comment] 2023-02-18 06:47
Closing as duplicate of #338 which is more actionable.

**Closed by alice-i-cecile** 2023-02-18 06:47 UTC
Labels: dev-ex, architectural

**Comment by TimJentzsch** [comment] 2023-02-18 09:38
I think #368 is the replacement issue here

**Comment by alice-i-cecile** [comment] 2023-02-18 14:23
Oops, absolutely. Triage on mobile is hard.
