### ISSUE TITLE
Replace `bevy_pancam` with our own camera implementation

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#155] opened 2022-12-26 19:11 UTC
In the long term, it will be beneficial to have full customization capabilities with our own camera implementation, instead of relying on crates.

We could potentially use `leafwing-input-manager` for the camera controls.

**Comment by bzm3r** [comment] 2022-12-26 20:54
@alice-i-cecile This is not `grab-bag` levels of difficulty 🤨 😆

**Comment by bzm3r** [comment] 2022-12-26 20:55
@TimJentzsch Darn, also I think this is a bit of a duplicate of: https://github.com/Leafwing-Studios/Emergence/issues/113

**Comment by wallamide** [comment] 2022-12-27 18:42
Since I started a little work on this I'll leave some info on what will be needed for this: 
- We will need to update the `leafwing-input-manager` source to include mouse motion in the egui context handling [in this function](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L88). 
- Fixing the above function may require updating how mouse motion is handled by the input manager's [`input_streams`](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/input_streams.rs#L295) to ensure improved performance and the ability to filter the mouse motion like other mouse inputs have been filtered in `systems` [here](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L83) and [here](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L94).
- Once doing the above we should be able to just use the input manager in our camera system.

**Comment by wallamide** [comment] 2022-12-27 18:42
Since I started a little work on this I'll leave some info on what will be needed for this:

- We will need to update the leafwing-input-manager source to include mouse motion in the egui context handling [in this function](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L88).
- Fixing the above function may require updating how mouse motion is handled by the input manager's [input_streams](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/input_streams.rs#L295) to ensure improved performance and the ability to filter the mouse motion like other mouse inputs have been filtered in systems [here](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L83) and [here](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/1eeb0854694ecbee835a531474b809ee48979623/src/systems.rs#L94).
- Once doing the above we should be able to just use the input manager in our camera system.

**Comment by alice-i-cecile** [comment] 2023-02-05 02:23
Done!

**Closed by alice-i-cecile** 2023-02-05 02:23 UTC
Labels: dependencies, dev-ex
